apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-dev
  labels:
    app: patient-service-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service-dev
  template:
    metadata:
      labels:
        app: patient-service-dev
    spec:
      containers:
      - name: patient-service
        image: host.minikube.internal:5000/patient_service_dev:latest  # Replace with your Docker image
        ports:
        - containerPort: 8000
        env:
        - name: DB_DRIVER_DEV
          value: "ODBC Driver 17 for SQL Server"
        - name: DB_SERVER_DEV
          value: "192.168.188.172"
        - name: DB_DATABASE_DEV
          value: "patient_service_dev"
        - name: DB_DATABASE_PORT
          value: "1433"
        - name: DB_USERNAME_DEV
          value: "fypcom_fypcom"
        - name: DB_PASSWORD_DEV
          value: "Fyppear@1"
        volumeMounts:
        - name: log-volume
          mountPath: /app/logs  # Path inside the container
      volumes:
      - name: log-volume
        hostPath:
          path: /home/VMadmin/FYP_microservices/PEAR_patient_service/logs  # Path on the host machine
          type: DirectoryOrCreate  # Ensures directory is created if it doesn’t exist
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service-dev
spec:
  selector:
    app: patient-service-dev
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort
