apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-dev
  labels:
    app: patient-service-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service-dev
  template:
    metadata:
      labels:
        app: patient-service-dev
    spec:
      containers:
      - name: patient-service
        image: host.minikube.internal:5000/patient_service_dev:latest  # Replace with your Docker image
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

        volumeMounts:
        - name: log-volume
          mountPath: /app/logs  # Path inside the container
      volumes:
      - name: log-volume
        hostPath:
          path: /home/VMadmin/FYP_microservices/PEAR_patient_service/logs  # Path on the host machine
          type: DirectoryOrCreate  # Ensures directory is created if it doesn’t exist
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service-dev
spec:
  selector:
    app: patient-service-dev
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort
