# All Filebeat logs will be sent to the ELK stack via Logstash.
# This DaemonSet will run Filebeat on each node in the cluster to collect logs.
# Ensure that the ELK stack is set up to receive logs from Filebeat. Please change output.logstash accordingly.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.17.14
        args: ["-c", "/etc/filebeat.yml", "-e"]
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          subPath: filebeat.yml
        - name: logs
          mountPath: /home/VMadmin/FYP_microservices/PEAR_patient_service/logs
      volumes:
      - name: config
        configMap:
          name: filebeat-config
      - name: logs
        hostPath:
          path: /home/VMadmin/FYP_microservices/PEAR_patient_service/logs


# Define ConfigMap for Filebeat configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: filestream
      enabled: true
      paths:
        - /home/VMadmin/FYP_microservices/PEAR_patient_service/logs/*.log

    output.logstash:    
      hosts: ["192.168.188.184:5044"]