# app/models/__init__.py
from .allergy_reaction_type_model import AllergyReactionType
from .allergy_type_model import AllergyType
from .patient_allergy_mapping_model import PatientAllergyMapping
from .patient_allocation_model import PatientAllocation
from .patient_assigned_dementia_list_model import PatientAssignedDementiaList
from .patient_assigned_dementia_mapping_model import PatientAssignedDementiaMapping
from .patient_attendance_model import PatientAttendance
from .patient_doctor_note_model import PatientDoctorNote
from .patient_guardian_model import PatientGuardian
from .patient_guardian_relationship_mapping_model import (
    PatientGuardianRelationshipMapping,
)
from .patient_highlight_model import PatientHighlight
from .patient_highlight_type_model import PatientHighlightType
from .patient_list_diet_model import PatientDietList
from .patient_list_education_model import PatientEducationList
from .patient_list_language_model import PatientListLanguage
from .patient_list_livewith_model import PatientLiveWithList
from .patient_list_occupation_model import PatientOccupationList
from .patient_list_pet_model import PatientPetList
from .patient_list_religion_model import PatientReligionList
from .patient_medical_diagnosis_list_model import PatientMedicalDiagnosisList
from .patient_medical_history_model import PatientMedicalHistory
from .patient_medication_model import PatientMedication
from .patient_mobility_list_model import PatientMobilityList
from .patient_mobility_mapping_model import PatientMobility
from .patient_model import Patient
from .patient_patient_guardian_model import PatientPatientGuardian
from .patient_photo_list_model import PatientPhotoList
from .patient_photo_model import PatientPhoto
from .patient_prescription_list_model import PatientPrescriptionList
from .patient_prescription_model import PatientPrescription
from .patient_privacy_level_model import PatientPrivacyLevel
from .patient_social_history_model import PatientSocialHistory
from .patient_vital_model import PatientVital
from .social_history_sensitive_mapping_model import SocialHistorySensitiveMapping
from .patient_problem_list_model import PatientProblemList
from .patient_problem_model import PatientProblem
# Import other models as needed
